# This is the production build, without a live mount of the app directory
web:
  build: .
  ports:
    - "5000:5000"
  links:
  - mongodb
  restart: always

mongodb:
  build: ./containers/mongodb
  restart: always
